---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-sample
  template:
    metadata:
      labels:
        app: app-sample
    spec:
      containers:
      - image: app:latest
        name: app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-sample
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: app-sample
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: app-sample
spec:
  to:
    kind: Service
    name: app-sample
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
