apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: app
  namespace: myapp
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: quay.io/fmissi/ubuntu
    importPolicy:
      importMode: PreserveOriginal
      # importMode: Legacy
    name: latest
    referencePolicy:
      type: Source
