apiVersion: image.openshift.io/v1
kind: ImageStreamImport
metadata:
  name: app
  namespace: myapp
spec:
  import: true
  images:
  - from:
      kind: DockerImage
      name: quay.io/fmissi/ubuntu
    to:
      name: latest
    referencePolicy:
      type: Source
    importPolicy:
      importMode: PreserveOriginal
      # importMode: Legacy
